### ISSUE TITLE
Backprots from Bitcoin

### ISSUE THREAD

**Issue by CharesFang** [BTCGPU/BTCGPU#437]
We recently investigated the Bitcoin issues which are related to privacy protection, vulnerability patches, or security enhancements. We have also checked the `BTCGPU` source code. Results show that these issues and their PRs are not backported yet. Henceforth, we suggest that `BTCGPU` should backport the PRs listed below for the considerations of software security and integrity. 

- [ ] Bitcoin [PR#17906](https://github.com/bitcoin/bitcoin/pull/17906), avoid uninitialized reads.
- [ ] Bitcoin [PR#16572](https://github.com/bitcoin/bitcoin/pull/16572), fix a `Char` variable used as `Bool`.
- [ ] Bitcoin [PR#16251](https://github.com/bitcoin/bitcoin/pull/16251), improve `signrawtransaction` error reporting.
- [ ] Bitcoin [PR#15337](https://github.com/bitcoin/bitcoin/pull/15337), fix segfault.
- [ ] Bitcoin [PR#15323](https://github.com/bitcoin/bitcoin/pull/15323), fix race condition in `mempool_persist.py`.
- [ ] Bitcoin [PR#15305](https://github.com/bitcoin/bitcoin/pull/15305), fix crash when disconnecting fail.
- [ ] Bitcoin [PR#15039](https://github.com/bitcoin/bitcoin/pull/15039), avoid leaking `nLockTime` fingerprint.
- [ ] Bitcoin [PR#14993](https://github.com/bitcoin/bitcoin/pull/14993), fix data race in `InterruptRPC()`.

Some of these issues and PRs are not severe security-related, but backports can avoid the chaos ecosystem of Bitcoin-forked projects and the potential vulnerabilities in the future. 

Reported by `de957ad9679f28a38f02f00cc7928bce8fb424882ff060a3c09c32895b1474cc`.

**Comment by CharesFang** [comment]
- [ ] Bitcoin [PR#15235](https://github.com/bitcoin/bitcoin/pull/15235) should also be backported to prevent that a private key was still loaded when it was disabled.

**Comment by h4x3rotab** [comment]
Hey Chares, thanks for your suggestions! We are working on upgrading to v0.21 which will include most of the changes you suggested to add. Please see PR #438 and issue #433 for more details.

**Comment by Jamesfrancs** [comment]
Waiting for 0.21 release Kindly have a look at it. (Pull request )@h4x3rotab @CharesFang @www222fff
